### ISSUE TITLE
Integration-Page-Temoignage-Version-Desktop

### ISSUE THREAD

**Issue by abdelkarim-moussi** [abdelkarim-moussi/Brief3-ImmoView-une-plateforme-immobili-re-innovante#13]

**Comment by AHLALLAY** [comment]
Coding une page contient :
* header comme un contenaire du logo, et bar de navigation avec un button de contact (tache pour tous le monde).
* une image sous la bar de navigation.
* premier section comme un contenaire des témoignages que serons divisé en deux ligne, chaque ligne contenu deux témoigne , et en haut de ce section  il y a un titre.
* deuxième section comme un contenaire de formulaire pour un nouveau témoigne.
* en fin le footer contient trois division, le premier pour un logo à coté d'un text qui parle sur le site, le deuxième pour les liens rapide, le troixième pour un formulaire de l'inscription au bulltien d'information, et une partie au dessu contient les copyright.
